@extends('layouts.app')

@section('title', 'Syscal')

@section('content')
    <div class="container">
        <div class="row">
			<div class="col-lg-2 col-md-12">
				@include('partials/leftsidebar/hulp')
				@include('partials/leftsidebar/partners')
			</div>
            <div class="col-lg-7 col-sm-12">
                <h1>Syscal</h1>
				<p>
					<h3>
						@lang('syscal.system')
					</h3>
				</p>
				<p>
					@lang('syscal.system-text')
				</p>
				<p>
					<b>
						@lang('syscal.operating')
					</b>
				</p>
				<p>
					@lang('syscal.operating-text')
				</p>
				<p>
					<b>
						@lang('syscal.modifications')
					</b>
				</p>
				<p>
					@lang('syscal.modifications-text')
				</p>
				<p>
					<b>
						@lang('syscal.disturbances')
					</b>
				</p>
				<p>
					@lang('syscal.disturbances-text')
				</p>
				<p>
					<b>
						@lang('syscal.updates')
					</b>
				</p>
				<p>
					@lang('syscal.updates-text')
				</p>
				<p>
					<b>
						@lang('syscal.virus')
					</b>
				</p>
				<p>
					@lang('syscal.virus-text')
				</p>
				<p>
					<b>
						@lang('syscal.backups')
					</b>
				</p>
				<p>
					@lang('syscal.backups-text')
				</p>
				<p>
					<b>
						@lang('syscal.availabilty')
					</b>
				</p>
				<p>
					@lang('syscal.availabilty-text')
				</p>
				<p>
					<b>
						@lang('syscal.deployment')
					</b>
				</p>
				<p>
					@lang('syscal.deployment-text')
				</p>
				<p>
					<b>
						@lang('syscal.hardware')
					</b>
				</p>
				<p>
					@lang('syscal.hardware-text')
				</p>
				<p>
					<b>
						@lang('syscal.backoffice')
					</b>
				</p>
				<p>
					@lang('syscal.backoffice-text')
				</p>
			</div>
			<div class="col-lg-3 col-md-12">
				@include('partials/rightsidebar/syscal')
                @include('partials/rightsidebar/isl')				
			</div>
        </div>
    </div>
@endsection